### ISSUE TITLE
BrowserslistError: Unknown version 0 of and_chr

### ISSUE THREAD

**Issue by finico** [ai/browserslist#110]
**Steps to reproduce**
1. browserslist@1.5.2 postcss@5.2.11 webpack@2.2.0
2. browserslist config in the package.json
```json
...
"browserslist": [
    "> 1% in RU",
    "last 2 versions"
]
...
```
3. postcss.config.js is simple
```js
module.exports = {
    plugins: [
        require('postcss-import')(),
        require('autoprefixer')()
    ]
};
```
4. `NODE_ENV=production webpack --hide-modules --bail` throws

```
ERROR in ./styles/index.css
Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown version 0 of and_chr
    at error (~/{path_to_project}/node_modules/browserslist/index.js:29:11)
    at Function.select (~/{path_to_project}/node_modules/browserslist/index.js:555:21)
    at ~/{path_to_project}/node_modules/browserslist/index.js:180:41
    at Array.forEach (native)
    at browserslist (~/{path_to_project}/node_modules/browserslist/index.js:169:13)
    at isSupported (~/{path_to_project}/node_modules/caniuse-api/dist/index.js:75:10)
    at ~/{path_to_project}/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:87:66
...
```

**PS**
* NODE_ENV != production -> ok
* not use "> 1% **in RU**" -> ok
* use "> 1% **in US**" -> not ok

**Comment by ai** [comment]
What `caniuse-db` version do you use? Please update if it is not latest.

**Comment by finico** [comment]
@ai 
```
└─┬ autoprefixer@6.6.1
  └── caniuse-db@1.0.30000613
```

**Comment by ai** [comment]
And what `caniuse-db` are used inside `browserslist`? Seems like Autoprefixer and Browserslist use different versions.

**Comment by finico** [comment]
@ai I see only one version of caniuse-db
```
> du -a node_modules | grep "caniuse-db\/package\.json"
8       node_modules/caniuse-db/package.json
```

```
> npm ls caniuse-db
└─┬ autoprefixer@6.6.1
  └── caniuse-db@1.0.30000613
```

How could I influence version of caniuse-db for browserslist?

**Comment by ai** [comment]
Try to find any `caniuse-db` directory in `node_modules`. Maybe `caniuse-api` contains different version?

**Comment by finico** [comment]
@ai 
both of `caniuse-db` and `caniuse-api` contains once
```
> npm ls caniuse-api
└─┬ css-loader@0.26.1
  └─┬ cssnano@3.10.0
    └─┬ postcss-merge-rules@2.1.1
      └── caniuse-api@1.5.2 
```
```
> du -a node_modules | grep "caniuse-api\/package\.json"
8       node_modules/caniuse-api/package.json
```

**Comment by ai** [comment]
Strange. You query work on my system. Could you create small project to reproduce?

**Comment by finico** [comment]
@ai https://github.com/finico/browserslist-reproduce

**Comment by ai** [comment]
Thanks, I will look tomorrow

**Comment by ai** [comment]
Fixed ac5071b. Thanks for report.

**Comment by ai** [comment]
Released in 1.6

**Comment by finico** [comment]
@ai Thanks

**Comment by ai** [comment]
Technically it was Can I Use mistake. But it is hard to fix it there. So I add hack to Browserslist.

@ben-eb maybe we will fix it in you project. Can I use had version 0 in countries statistics, but 55 in global data.

**Comment by stevenvachon** [comment]
I'm still getting this error consistently, but only on CI (Linux) and never local (macOS).

**Comment by ai** [comment]
@stevenvachon I recommend to use `yarn`, because it lock version to `yarn.lock` and you can find what versions are used (also yarn is few times faster).

**Comment by stevenvachon** [comment]
I just noticed that my CI server was set to use node v6.3.0. The problem is solved by switching to 7.4.0, which likely forces a newer version of npm.

**Comment by stevenvachon** [comment]
Scratch that -- it was just a fluke. It started consistently failing again with the same error. Switching from `npm install` to `yarn` seems to be consistently working. Thanks!
