### ISSUE TITLE
Change last n version scheme to include all browsers listed on caniuse

### ISSUE THREAD

**Issue by hexalys** [ai/browserslist#98]
As previouly [mentioned](https://github.com/autoprefixer/autoprefixer.github.io/issues/9#issuecomment-269853775) for autoprefixer usage. Consider including current browsers with large market share such as Opera, UCBrowser etc.. (now classified as minor browser) as supported, by the `n` version scheme.

e.g. 'last 2 versions' should include Opera Mini, UCBrowser and Firefox for Android, Samsung...

**Comment by ai** [comment]
I think we should do it.

But because it is major change, let’s wait for a while.

**Comment by ai** [comment]
@hzoo are you agree with this changes? It will affect to `babel-present-env` too.

**Comment by TCotton** [comment]
That seems to be a big (breaking?) change. Opera Mini has a "pick'n'mix" approach to CSS features. Few of us write code with that browser in mind (whether we should or not is a separate discussion). I don't know how this would work in practice

**Comment by ai** [comment]
@TCotton sure, it will be a major release for Browserslist and for Autoprefixer.

**Comment by ai** [comment]
Done 0e145a6

**Comment by ebidel** [comment]
Just to play devils advocate...

I wonder if https://github.com/ai/browserslist/commit/0e145a618627fefde0b16fc832c1acc9c95da3c6 will have a greater negative impact than a positive one? IOW, tons of people use `latest n versions` and will continue to do so after a major release. With this change, they're going to be potentially pushing 3-4x more bytes per CSS feature and never realize it. Extrapolating that out to a large CSS file could mean significant delays to first paint and other page load metrics :(

The feature differences between the latest major browsers and all browsers can be large. Would it make more sense to support a (new) opt-in query?

**Comment by ai** [comment]
@ebidel prefixes are very easy task for gzip. I think bundle sizes become bigger only in 1-5%.

**Comment by ebidel** [comment]
Very true about gzip. It would be interesting to real numbers from the wild. [26% of the web](http://httparchive.org/trends.php#perCompressed) still doesn't compress responses.

More bytes are more bytes :)
- larger responses cause more decompression work, increased memory, cpu time, etc.
- larger responses increase issues with browser caching.

Mobile makes all of this worse. I've seen the HTTP cache take anywhere from 50-100ms to return a fresh asset on a Nexus 5 (no network cost). That's also without main thread contention. I'd imagine that number grows with resource size and main thread contention but haven't looked at that closely.

**Comment by ai** [comment]
@ebidel maybe real benchmark will be better. Could you take your companies CSS and compare it for current behaviour and new behaviour (you can emulate 2.0 behaviour by `last 2 chrome version, …`).

**Comment by ebidel** [comment]
I don't really have a meaningful file to test with. Something like a news site might be interesting and representative. I'll try to through in some time, but things are pretty busy between now and prepping for Google I/O.

**Comment by ai** [comment]
I compared (minified, no gzip):

* `last 2 versions` of any main browsers: **276,9 KB**
* `last 2 versions` of all browsers: **287,8 KB**.

Result is 4% extra size. I think it is very good price for Internet which will be ready for any browsers (it is sad that most developers ignores browsers not popular in US, but have big market in other countries like Opera or Chinese browsers).

**Comment by ai** [comment]
@ebidel I compared (minified, no gzip):

* `last 2 versions` of any main browsers: **276,9 KB**
* `last 2 versions` of all browsers: **287,8 KB**.

Result is 4% extra size. I think it is very good price for Internet which will be ready for any browsers (it is sad that most developers ignores browsers not popular in US, but have big market in other countries like Opera or Chinese browsers).

**Comment by ebidel** [comment]
Nice! Thanks for looking into some numbers in a large stylesheet.  I think you're right about the 4%. There are bigger performance bottlenecks on the web. ~10kB is pretty chill in the grand scheme of web bloat :)

**Comment by Kovensky** [comment]
Very late comment, but some notes:

* `babel-preset-env` does use browserslist for calculating supported browsers, but it only uses data for a specific list of browsers (https://github.com/babel/babel-preset-env/blob/20ddb722/src/index.js#L49; if it's not in this object, it's ignored).

* matching _all_ browsers with `last n versions` can make some linters like `doiuse` very angry and possibly impossible to use without restricting the matched set.

**Comment by ai** [comment]
Yeap, it is too late 😅

**Comment by zslabs** [comment]
👋 Coming over from https://github.com/postcss/autoprefixer/issues/838, is there a setting we could use to get back the major browsers only that were supported previously? Thanks!

**Comment by ai** [comment]
Nope, because previous behavior is a bad practice in general.

In if you want it, write browsers by name.
